apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgw-backend
  labels:
    app: bgw-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgw-backend
  template:
    metadata:
      labels:
        app: bgw-backend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: ugw-backend-pod
        image: dr.fosefx.com/bgw-backend:1.0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 59091
---
apiVersion: v1
kind: Service
metadata:
  name: bgw-expose-service
spec:
  selector:
    app: bgw-backend
  ports:
  - protocol: TCP
    port: 59091
    targetPort: 59091
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bgw-ingress
  annotations:  
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: proxy.fosefx.com
    http:
      paths:
      - path: /
        backend:
          serviceName: bgw-expose-service
          servicePort: 59091
