---
kind: pipeline
name: default

steps:
  - name: build container
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      TEST_LEHRER_CREDS:
        from_secret: TEST_LEHRER_CREDS
      TEST_LEHRER_P:
        from_secret: TEST_LEHRER_P
      TEST_LEHRER_U:
        from_secret: TEST_LEHRER_U
      TEST_SCH_CREDS:
        from_secret: TEST_SCH_CREDS
      TEST_SCH_P:
        from_secret: TEST_SCH_P
      TEST_SCH_U:
        from_secret: TEST_SCH_U
    commands:
      - docker build --build-arg TEST_LEHRER_CREDS=${TEST_LEHRER_CREDS} --build-arg  TEST_LEHRER_P=${TEST_LEHRER_P} --build-arg  TEST_LEHRER_U=${TEST_LEHRER_U} --build-arg  TEST_SCH_CREDS=${TEST_SCH_CREDS} --build-arg  TEST_SCH_P=${TEST_SCH_P} --build-arg  TEST_SCH_U=${TEST_SCH_U} -t fosefx/bettergymwue-backend:${DRONE_COMMIT_SHA} backend

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - master
---
kind: secret
name: TEST_LEHRER_CREDS
get:
  path: secrets/data/docker
  name: TEST_LEHRER_CREDS

---
kind: secret
name: TEST_LEHRER_P
get:
  path: secrets/data/docker
  name: TEST_LEHRER_P
---
kind: secret
name: TEST_LEHRER_U
get:
  path: secrets/data/docker
  name: TEST_LEHRER_U

---
kind: secret
name: TEST_SCH_CREDS
get:
  path: secrets/data/docker
  name: TEST_SCH_CREDS
---
kind: secret
name: TEST_SCH_P
get:
  path: secrets/data/docker
  name: TEST_SCH_P

---
kind: secret
name: TEST_SCH_U
get:
  path: secrets/data/docker
  name: TEST_SCH_U
