---
kind: pipeline
name: default

steps:
  - name: test
    image: node
    commands:
      - curl 172.17.0.1:59092/v2/version --verbose
      - npm ci
      - npm test

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - master
