---
kind: pipeline
name: default

steps:
  - name: test
    environment:
      TEST_LEHRER_CREDS:
        from_secret: TEST_LEHRER_CREDS
      TEST_LEHRER_P:
        from_secret: TEST_LEHRER_P
      TEST_LEHRER_U:
        from_secret: TEST_LEHRER_U
      TEST_SCH_CREDS:
        from_secret: TEST_SCH_CREDS
      TEST_SCH_P:
        from_secret: TEST_SCH_P
      TEST_SCH_U:
        from_secret: TEST_SCH_U
    image: node
    commands:
      - cd backend
      - npm ci
      - npm test

  - name: build
    image: docker
    commands:
      - docker build -t fosefx/bettergymwue-ci:${DRONE_COMMIT_SHA} .
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: run
    image: dockersock
    commands:
      - docker run -d -p $(wget -qO- https://proxy.fosefx.com/cd/BetterGymWue/${DRONE_COMMIT_SHA}):59091 -i --rm fosefx/bettergymwue-ci:${DRONE_COMMIT_SHA}
    volumes:
      - name: dockersock
        path: /var/run/docker.sock


volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - master
