---
kind: pipeline
name: default

steps:
  - name: build container
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - curl ${DRONE_MACHINE}:59092/v2/version --verbose
      - docker build -t fosefx/bettergymwue-backend:${DRONE_COMMIT_SHA} backend

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - master
