---
kind: pipeline
name: default

steps:
  - name: build container
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - bash backend/build.sh ${DRONE_COMMIT_SHA}

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - master
