version: '3'
services:
  redis:
    image: redis
    container_name: cache
    expose:
    - 6379
  rust-backend:
    build: core
    depends_on:
    - redis
    ports:
    - 8800:8000
    environment:
    - REDIS_PATH=redis://cache
