export const PREFILLS = [
  "Kunst",
  "Theater",
  "ECDL",
  "Sport",
  "Garten AG",
  "Roboter AG",
  "Spiele AG",
  "Lernzeit Deutsch",
  "Lernzeit Englisch",
  "Lernzeit Mathe",
  "Mathe",
  "Deutsch",
  "Englisch",
  "Physik",
  "Biologie",
  "PCL",
  "Erdkunde",
  "Philosophie",
  "Musik",
  "Religion",
  "Religion",
  "Französisch",
  "Latein",
  "Kunst-Musik",
  "Jugendwelten",
  "Bio-Chemie",
  "Informatik",
  "SoWi",
  "Geschichte",
  "Pädagogik",
  "Italienisch",
  "Vertiefung Mathe",
  "Vertiefung Deutsch",
  "Vertiefung Englisch",
  "Philosophie",
  "Lernzeit",
  "Vertiefung",
  "Chemie"
];
